import '../styles/globals.css'
import 'jodit/build/jodit.min.css';
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Providers from '@/lib/Providers'
import { dbConnect } from '@/lib/dbConnect'
import Header from '@/components/Main/Header'
import Footer from '@/components/Main/Footer'
import Toast from '@/lib/Toast'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'TechnoEvo',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Toast />
          <Header />
          <div className='container p-5 max-w-7xl min-h-screen'>
            {children}
          </div>
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
