server:
  port: 5000
  origin: 'http://localhost:3000'

jwt:
  # expiresIn: 10
  expiresIn: 900
  refreshExpiresIn: 604800
  cookieExpiresIn: 604800

app:
  fallbackLanguage: 'en'
  name: 'TechnoEvo'
  version: 'v0.1'
  description: 'Official TechnoEvo API'
  appUrl: 'http://localhost:5000'
  frontendUrl: 'http://localhost:3000'
  sameSite: true

mail:
  host: 'smtp.mailtrap.io'
  port: 2525
  user: 'f4a511d60957e6'
  pass: '7522797b96cef0'
  from: 'TechnoEvo'
  fromMail: 'TechnoEvo@gmail.com'
  preview: true
  secure: false
  ignoreTLS: true
  queueName: 'TechnoEvo-mail'